# -*- coding: utf-8 -*-
"""CS Project - Vidit Jain, Shesh Shiromani, Rehaan Sejwal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1KRuDpV1ZpsYKdtJR5NK2GDcipU-tcQ
"""

import random

truths = [
    "What is your biggest fear?",
    "Have you ever lied to your best friend?",
    "What's the most embarrassing thing you've ever done?",
    "If you could change one thing about yourself, what would it be?",
    "Have you ever kept a secret from your parents?"
]

dares = [
    "Do 10 push-ups!",
    "Sing your favorite song out loud!",
    "Dance for 30 seconds without music in front of class!",
    "Speak in a funny accent for the next 2 minutes!"
]

total = 0
print("Welcome to the 21 Dares Game!")

while total < 21:
    u = input("Your turn! Enter 1, 2, or 3: ").strip()
    if u not in ['1', '2', '3']:
        print("Invalid input. Please enter 1, 2, or 3.")
        continue

    u = int(u)
    total += u
    print("Current total:", total)

    if total == 20:
        print("Computer lost!")
        break

    if total >= 21:
        print("Game Over!")
        choice = input("You reached 21! Choose 'truth' or 'dare': ").strip().lower()
        if choice == 'truth':
            print("Truth:", random.choice(truths))
        elif choice == 'dare':
            print("Dare:", random.choice(dares))
        else:
            print("Invalid choice. No challenge for you!")
        break

    if total == 18:
        c = random.randint(1, 2)
    else:
        c = random.randint(1, 3)


    print("Computer chose:", c)
    total += c
    print("Current total:", total)

    if total >= 21:
        print("Game Over! You lost!")
        break